name: Maintain the hygiene of a repo

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: {node-version: 13.x}
      - uses: actions/cache@v1
      - run: npm ci
        env:
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
      