name: Maintain the hygiene of a repo

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  alert:
    runs-on: ubuntu-latest
    name: hygiene run
    steps:
       - uses: actions/checkout@v2
       - name: Use Node.js
         uses: actions/setup-node@v1
         with:
           node-version: '12.x'
       - name: Install dependencies
         run: npm ci
        env:
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
  
