name: Maintain the hygiene of a repo

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  alert:
    runs-on: ubuntu-latest
    name: hygiene run
    steps:
      - uses: sid-ah/hygiene/actions@master
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          check-latest: true
      - run: npm install
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
