name: Maintain the hygiene of a repo

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  alert:
    runs-on: ubuntu-latest
    name: hygiene run
    steps:
       - uses: actions/checkout@v2
       - run: npm ci
        env:
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
