name: Maintain the hygiene of a repo

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  alert:
    runs-on: ubuntu-latest
    name: hygiene run
    steps:
      - uses: sid-ah/hygiene/actions@master
        env:
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: install dependencies
        run: npm ci

